# Generated by Django 5.0.3 on 2024-03-31 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('grid_size', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('row', models.PositiveSmallIntegerField()),
                ('clue', models.CharField(blank=True, max_length=30)),
                ('crossmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.crossmap')),
            ],
        ),
    ]
