# Generated by Django 5.0.3 on 2024-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossmap',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crossmap',
            name='picture',
            field=models.ImageField(default='crossword_default.png', upload_to='crossword_pictures'),
        ),
    ]
