# Generated by Django 5.0.3 on 2024-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0002_crossmap_level_crossmap_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossmap',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='clue',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
