# Generated by Django 5.0.3 on 2024-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0005_wordresult_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordresult',
            name='wordCheck',
            field=models.BooleanField(default=0),
        ),
    ]
