# Generated by Django 5.0.3 on 2024-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='None', max_length=600),
        ),
    ]
